### ISSUE TITLE
Improve exception logging in Flask app

### ISSUE THREAD

**Issue by bnaul** [cesium-ml/cesium#107]
Currently the error messages written to the log file are very uninformative, along the lines of "An error has occurred." The actual text of the exception is usually printed to stdout, which is usually lost forever. This is problematic for testing and also will eventually be a problem in production.

**Comment by acrellin** [comment]
The actual error doesn't even always get printed to stdout! But yeah similar issue.

**Comment by stefanv** [comment]
Hopefully the Tornado exceptions are logged more clearly.  If not, please open a new issue.
