### ISSUE TITLE
Look into unifying `verify_new_script` and `generate_custom_feature` logic

### ISSUE THREAD

**Issue by stefanv** [cesium-ml/cesium#146]

**Comment by bnaul** [comment]
Somewhat related: `verify_new_script` uses data living in `cfg.SAMPLE_DATA_PATH`, but there seems to be a lot of unnecessary stuff in there; furthermore, a lot of it is duplicates of the test data in `mltsp/tests/data`. We should figure out what we need to keep and what can be removed.
