### ISSUE TITLE
Website not accessible over https

### ISSUE THREAD

**Issue by Carreau** [cesium-ml/cesium#175]
Sorry bad habit of typing domain by hand :-P

**Comment by Carreau** [comment]
Pingin @bnaul who is explicitly ignoring me.

**Comment by bnaul** [comment]
Blame GitHub: https://github.com/isaacs/github/issues/156.

https://cesium-ml.github.io works but not https://cesium.ml. Don't believe there's anything we can do about this.

**Comment by Carreau** [comment]
Fair enough.
