### ISSUE TITLE
problem in the webapp startup script "watch_logs.py"

### ISSUE THREAD

**Issue by geraldstanje** [cesium-ml/cesium#178]
Hi, 
im on osx with docker for mac: https://docs.docker.com/docker-for-mac/
i run the example as follows: http://cesium.ml/

it seems the docker image is broken:
```
web_1     | mkdir -p ~/.local/cesium/logs
web_1     | ./tools/watch_logs.py
web_1     | Traceback (most recent call last):
web_1     |   File "<string>", line 1, in <module>
web_1     |   File "cesium_app/models.py", line 16
web_1     |     db = pw.PostgresqlDatabase(**cfg['database'], autocommit=True,
web_1     |                                                 ^
web_1     | SyntaxError: invalid syntax
cesium_web_1 exited with code 1
```

**Comment by bnaul** [comment]
Hi Gerald,

Fixed this in cesium-ml/cesium_web@cb7ebcc09417ffb12801c4723082b1aebbf66de8, rebuilding the Docker image now...will close when it's been pushed.

Brett

**Comment by geraldstanje** [comment]
Hi Brett, 
great thanks! 
could you tell me where you upload the Docker image?

**Comment by geraldstanje** [comment]
@bnaul is the image already up? could you send me the link?

**Comment by stefanv** [comment]
The new image is up, and can be fetched with docker-compose pull

**Comment by geraldstanje** [comment]
ok that works.

I uploaded the Dataset Header (example-headers.dat) and Data Tarball (example-series.tar.gz) according to the doc:

It shows me the following issue when uploading the dataset:
Error: invalid literal for int() with base 10: ''

**Comment by bnaul** [comment]
Glad it's working now. The project issue is one we've already noted (cesium-ml/cesium_web#9) so I'll close this for now.
