### ISSUE TITLE
Add proper README.md

### ISSUE THREAD

**Issue by fperez** [cesium-ml/cesium#187]
Should include
- [ ] What is the project: short description of purpose
- [ ] License notice (actual license is in COPYING)
- [ ] Installation instructions from packages
- [ ] Installation instructions from source
- [ ] Link to `cesium_web` and clarify distinction
- [ ] Link to examples page on website

**Comment by arkwave** [comment]
@jiesuncal and myself are working on this!

**Comment by stefanv** [comment]
@arkwave Great! Please move this item from 'TODO' to 'In Progress' in the projects tab.
