### ISSUE TITLE
Failing to pip install cesium

### ISSUE THREAD

**Issue by pkgandhi** [cesium-ml/cesium#214]
Hello,

I am not able to install the cesium package through pip install even though all the dependencies are satisfied. I am getting something like following. Does anyone know what is going on here:

![image](https://cloud.githubusercontent.com/assets/12904022/19837293/7013428a-9e8d-11e6-82e4-844878e0c778.png)

Thanks!

**Comment by stefanv** [comment]
Thanks for the bug report, @pkgandhi.  Which commands did you run to generate the above?

If you haven't yet, please also try:

```
pip install --upgrade pip
pip install .
```

**Comment by pkgandhi** [comment]
@stefanv  : Pip says it is up to date!
Doing "pip install ." it says File setup.py not found. It is kind of bizarre, ain't it?

**Comment by stefanv** [comment]
Did you run `pip install .` in the Cesium source directory?

**Comment by pkgandhi** [comment]
Somehow I am not able to locate Cesium source directory. It is trying to collect from cache, but I am unable to locate it. Any ideas how to find it?

**Comment by pkgandhi** [comment]
@stefanv  I tried downloading source and doing pip install . - still did not work. Getting the following error: 

![image](https://cloud.githubusercontent.com/assets/12904022/19838218/fbceef64-9ea0-11e6-834c-bb72ebb41b79.png)

**Comment by bnaul** [comment]
Hi @pkgandhi, we don't officially support Windows so I'm not surprised that this isn't working. However, I'm willing to try and sort it out if you can provide us a little more information; there shouldn't be anything in the library that can't be made to work with a proper Windows development environment.

Can you try copy-pasting the entire output here (it would be better to provide the whole text in a ``` block instead of a screenshot)? The line you're giving us basically just says that an error occurred, but we need the rest of the traceback in order to see what in particular went wrong.

**Comment by pkgandhi** [comment]
Hi @bnaul, sure! Attached is the screenshot:

![image](https://cloud.githubusercontent.com/assets/12904022/19855964/afe311a4-9f4d-11e6-8b52-782dea61aec7.png)

![image](https://cloud.githubusercontent.com/assets/12904022/19855975/c26276e4-9f4d-11e6-9084-0719b8afacd0.png)

![image](https://cloud.githubusercontent.com/assets/12904022/19855979/ce0868b4-9f4d-11e6-8e75-b51e05de0664.png)

Attached are the screenshots. Let me know if these would help!

Thanks!

**Comment by bnaul** [comment]
Great, thanks for the expanded output. That error appears because you don't have a C compiler installed: our package has some features which are implemented in C and integrated into our Python code via `cython`. Here is a link that describes how to install a C compiler for Windows: https://github.com/cython/cython/wiki/CythonExtensionsOnWindows. I believe once you have a C compiler the package should compile and load correctly, but again, we haven't explicitly tested this.

I'm going to close this for now since this isn't a bug in `ceisum` per se, but feel free to keep commenting here. I personally would strongly recommend that you set up a Linux-like environment for your development, e.g. using Docker: https://docs.docker.com/engine/installation/windows/. But that's just my personal preference :).

**Comment by beeb** [comment]
Hey! Sorry to bring back this issue from the dead, coming back to this to say that I was unable to install cesium using `pip` on Windows 10. I have Anaconda and made a separate Python 3.6 environment for this, installed all the dependencies succesfully. I installed the Visual C++ build tools (2017) so I have a compiler available.

Unfortunately, the compilation fails, [here](https://pastebin.com/2b74Fp14) is what pip gives me.

So the first error is this:

    error: Command "C:\Program Files (x86)\Microsoft Visual 
    Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\vbersier\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\numpy\core\include -IC:\Users\vbersier\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\numpy\core\include -IC:\Users\vbersier\AppData\Local\conda\conda\envs\tensorflow\include -IC:\Users\vbersier\AppData\Local\conda\conda\envs\tensorflow\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tccesium\features\_lomb_scargle.c /Fobuild\temp.win-amd64-3.6\Release\cesium\features\_lomb_scargle.obj" failed with exit status 2
    Failed building wheel for cesium

Then this:

     error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\vbersier\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\numpy\core\include -IC:\Users\vbersier\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\numpy\core\include -IC:\Users\vbersier\AppData\Local\conda\conda\envs\tensorflow\include -IC:\Users\vbersier\AppData\Local\conda\conda\envs\tensorflow\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tccesium\features\_lomb_scargle.c /Fobuild\temp.win-amd64-3.6\Release\cesium\features\_lomb_scargle.obj" failed with exit status 2

        ----------------------------------------
    Command "C:\Users\vbersier\AppData\Local\conda\conda\envs\tensorflow\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\vbersier\\AppData\\Local\\Temp\\pip-install-rrr09t5v\\cesium\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\vbersier\AppData\Local\Temp\pip-record-lmdbgvey\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\vbersier\AppData\Local\Temp\pip-install-rrr09t5v\cesium\

I have no clue which other compiler to use for this, they seem to all not support Python > 3.4. Any help would be greatly appreciated! Thanks

**Comment by goldentom42** [comment]
Hi there, same here on windows 8.1 with the same compiler.

I'm usually able to build packages either from windows comand window or from a git bash.

Both give the exact same compiler error

![image](https://user-images.githubusercontent.com/17214417/46932424-f8cd5480-d04f-11e8-8526-cb92a2474623.png)

Thanks for your help, Olivier

**Comment by acrellin** [comment]
Hi @beeb and @goldentom42, 
[MinGW](https://mingw-w64.org/) works for Python 3.6.  Please try that and let us know if that solves your installation issues.

**Comment by PrathamSolanki** [comment]
I'm also encountering the same issue as @beeb  on Windows 10. I too have a similar Python 3.6 Anaconda environment. @beeb have you tried @acrellin 's solution with MinGW? Has it worked so I may do the same as well.

**Comment by beeb** [comment]
Please see [this how-to](https://github.com/cesium-ml/cesium/issues/275#issuecomment-429055148). I'm trying it right now

**Comment by PrathamSolanki** [comment]
Yeah worked for me as well!
