### ISSUE TITLE
How to install Cesium from Anaconda?

### ISSUE THREAD

**Issue by brylie** [cesium-ml/cesium#240]
I am trying to install Cesium from the Python 3.6 version of Anaconda, for x86_64 architecture. When searching for 'cesium', conda is unable to find the package.

How might I use conda to manage the installation of cesium?

**Comment by stefanv** [comment]
Cesium isn't packaged in conda, but you can install it using pip:

`pip install cesium`

As far as I know, conda does track pip installs to some extent.
