### ISSUE TITLE
Use pytest instead of nose

### ISSUE THREAD

**Issue by bnaul** [cesium-ml/cesium#242]
Would be nice to switch for 1) consistency w/ `cesium_web`, 2) better support going forward, 3) increased prettiness.

We don't use much `nose`-specific stuff so this should be easy. Currently just running `pytest` w/ the current suite gives:
```
Results (17.19s):
      54 passed
      19 error
```

**Comment by stefanv** [comment]
See also: https://github.com/cesium-ml/cesium_web/issues/132
