### ISSUE TITLE
Error: too many indices for array

### ISSUE THREAD

**Issue by friedlysol** [cesium-ml/cesium#253]
I'm loading up a larger dataset and I get this erro when loading into the model.

The header file looks like this:

filename,target
22090057.txt,a
22090282.txt,a
22109627.txt,a
22109630.txt,a
22110423.txt,a
22113257.txt,a
22126905.txt,a
22127034.txt,a
22128488.txt,a

Individual files look similair to:
12,1.53
13,1.64
14,1.64
15,1.66
16,1.74
17,1.76
18,1.82
19,1.90
20,1.96
21,1.95
22,1.96
23,2.03
24,2.07
25,2.09
26,2.17
27,2.20
28,2.26
29,2.40
30,2.44

Loading the demo data, or loading small subset of the data I have problem with works fine. Any suggestions?

**Comment by acrellin** [comment]
Can you provide the full traceback? And how large is the dataset?

**Comment by friedlysol** [comment]
Where do I get the traceback from? Nothing shows up in the console.

Here is the data I load:
https://github.com/friedlysol/cesium253

**Comment by friedlysol** [comment]
`web_1  | tornado.application - ERROR - Uncaught exception POST /dataset (127.0.0.1)
web_1  | HTTPServerRequest(protocol='http', host='192.168.2.214:9000', method='POST', uri='/dataset', version='HTTP/1.0', remote_ip='127.0.0.1', headers={'Host': '192.168.2.214:9000', 'X-Real-Ip': '192.168.2.24', 'X-Forwarded-For': '192.168.2.24', 'X-Forwarded-Proto': 'http', 'Connection': 'close', 'Content-Length': '38281', 'Origin': 'http://192.168.2.214:9000', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryxyvBlmfyUjp4zDSg', 'Accept': '*/*', 'Referer': 'http://192.168.2.214:9000/', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US,en;q=0.8', 'Cookie': 'auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MDEyNzkxMjAsInVzZXJuYW1lIjoidGVzdHVzZXJAZ21haWwuY29tIn0.o0v4Eeec73rqWePL2VHXmd170VMBxyOoVXDrw3Z_u2w'})
web_1  | Traceback (most recent call last):
web_1  |   File "/cesium_env/lib/python3.6/site-packages/tornado/web.py", line 1509, in _execute
web_1  |     result = method(*self.path_args, **self.path_kwargs)
web_1  |   File "/cesium_env/lib/python3.6/site-packages/tornado/web.py", line 2897, in wrapper
web_1  |     return method(self, *args, **kwargs)
web_1  |   File "/cesium/cesium_app/handlers/dataset.py", line 65, in post
web_1  |     headerfile_path)
web_1  |   File "/cesium_env/lib/python3.6/site-packages/cesium/data_management.py", line 149, in parse_and_store_ts_data
web_1  |     ts_path)
web_1  |   File "/cesium_env/lib/python3.6/site-packages/cesium/time_series.py", line 195, in __init__
web_1  |     if _ndim(self.time) == 1 and _ndim(self.measurement) == 2:
web_1  |   File "/cesium_env/lib/python3.6/site-packages/cesium/time_series.py", line 18, in _ndim
web_1  |     x = x[0]
web_1  | IndexError: too many indices for array
web_1  | ! App Error: too many indices for array
web_1  | tornado.application - ERROR - Uncaught exception POST /dataset (127.0.0.1)
web_1  | HTTPServerRequest(protocol='http', host='192.168.2.214:9000', method='POST', uri='/dataset', version='HTTP/1.0', remote_ip='127.0.0.1', headers={'Host': '192.168.2.214:9000', 'X-Real-Ip': '192.168.2.24', 'X-Forwarded-For': '192.168.2.24', 'X-Forwarded-Proto': 'http', 'Connection': 'close', 'Content-Length': '2511', 'Origin': 'http://192.168.2.214:9000', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryMkrrsw4JSTXYeHue', 'Accept': '*/*', 'Referer': 'http://192.168.2.214:9000/', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US,en;q=0.8', 'Cookie': 'auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MDEyNzkxMjAsInVzZXJuYW1lIjoidGVzdHVzZXJAZ21haWwuY29tIn0.o0v4Eeec73rqWePL2VHXmd170VMBxyOoVXDrw3Z_u2w'})
web_1  | Traceback (most recent call last):
web_1  |   File "/cesium_env/lib/python3.6/site-packages/cesium/data_management.py", line 89, in parse_headerfile
web_1  |     header = header.loc[short_fnames_to_include]
web_1  |   File "/cesium_env/lib/python3.6/site-packages/pandas/core/indexing.py", line 1312, in __getitem__
web_1  |     return self._getitem_axis(key, axis=0)
web_1  |   File "/cesium_env/lib/python3.6/site-packages/pandas/core/indexing.py", line 1472, in _getitem_axis
web_1  |     return self._getitem_iterable(key, axis=axis)
web_1  |   File "/cesium_env/lib/python3.6/site-packages/pandas/core/indexing.py", line 1036, in _getitem_iterable
web_1  |     self._has_valid_type(key, axis)
web_1  |   File "/cesium_env/lib/python3.6/site-packages/pandas/core/indexing.py", line 1395, in _has_valid_type
web_1  |     (key, self.obj._get_axis_name(axis)))
web_1  | KeyError: "None of [['22112265', '22125108', '22129307', '22055466', '22093850', '22093878', '22093882', '22098737', '22101947']] are in the [index]"
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/cesium_env/lib/python3.6/site-packages/tornado/web.py", line 1509, in _execute
web_1  |     result = method(*self.path_args, **self.path_kwargs)
web_1  |   File "/cesium_env/lib/python3.6/site-packages/tornado/web.py", line 2897, in wrapper
web_1  |     return method(self, *args, **kwargs)
web_1  |   File "/cesium/cesium_app/handlers/dataset.py", line 65, in post
web_1  |     headerfile_path)
web_1  |   File "/cesium_env/lib/python3.6/site-packages/cesium/data_management.py", line 135, in parse_and_store_ts_data
web_1  |     labels, meta_features = parse_headerfile(header_path, ts_paths)
web_1  |   File "/cesium_env/lib/python3.6/site-packages/cesium/data_management.py", line 91, in parse_headerfile
web_1  |     raise ValueError("Incomplete header file: make sure your "
web_1  | ValueError: Incomplete header file: make sure your header contains an entry for each time series file in the uploaded archive, and that the file names match the first column of the header.
web_1  | ! App Error: Incomplete header file: make sure your header contains an entry for each time series file in the uploaded archive, and that the file names match the first column of the header.
web_1  | tornado.application - ERROR - Uncaught exception POST /dataset (127.0.0.1)

`

**Comment by friedlysol** [comment]
Anything that I can do to further identify the problem?

**Comment by acrellin** [comment]
@friedlysol the issue is with the time series with only a single epoch. The minimum number of epochs per time series is two. We will update the error message to be more informative. Thanks for bringing this to our attention.
