### ISSUE TITLE
Multichannel

### ISSUE THREAD

**Issue by friedlysol** [cesium-ml/cesium#260]
I'm trying to figure out how to pass data for the same time series with multiple channels via cesium-web.

Is that passed in the header file?

**Comment by bnaul** [comment]
We currently don't support multichannel data in the web app, only in the `cesium` library. [This](http://cesium-ml.org/docs/auto_examples/plot_EEG_Example.html) example shows how to do an analysis using multichannel data using just the backend. We do intend to add this functionality so I'm leaving this issue open.
