### ISSUE TITLE
issue with dask

### ISSUE THREAD

**Issue by dmbee** [cesium-ml/cesium#277]
I get errors relating to get= keyword in dask when using featurize_time_series in cesium 

Testing is performed in Linux Mint 18.3 (Ubuntu 16.04) using python 2.7.12 and python 3.5.2 in clean virtual environments (virtualenv) using pip to install cesium. 

[cesium-errors.log.txt](https://github.com/cesium-ml/cesium/files/2601821/cesium-errors.log.txt)

**Comment by milesial** [comment]
Hi, check out https://github.com/cesium-ml/cesium/pull/276

**Comment by dmbee** [comment]
Thanks
