### ISSUE TITLE
Seizure detection example taking a long time to run

### ISSUE THREAD

**Issue by paulomaia20** [cesium-ml/cesium#281]
Hello,

I'm trying to run the example on seizure detection (http://cesium-ml.org/docs/auto_examples/plot_EEG_Example.html#sphx-glr-auto-examples-plot-eeg-example-py) and it's taking me a very long time to finish. The given example says that it takes "0 minutes 20.340 seconds" to finish, and my computer is pretty decent, so it should not take much more than a few minutes. I even tried using Google Collab's servers, but it's still very slow. 

I even tried deleting everything except the mean  of the signal (which is computed instantaneously using numpy) and it still takes a long time when used in the featurize_time_series function. 

Could I be having some issues with the dask scheduler? 

Also, I've been having a lot of RuntimeWarnings in this example:

" C:\Anaconda3\lib\site-packages\cesium\features\cadence_features.py:12: RuntimeWarning: divide by zero encountered in true_divide
  return (cads[2:] + cads[:-2]) / (cads[1:-1] - cads[:-2])" is this natural?

Best regards,

Paulo

**Comment by acrellin** [comment]
Closed in https://github.com/cesium-ml/cesium/commit/b924ef13031f0af5d215a82c2df6b58494b778d8

**Comment by acrellin** [comment]
Fixed in v0.9.11
