### ISSUE TITLE
New version of dask broke this library

### ISSUE THREAD

**Issue by George3d6** [cesium-ml/cesium#286]
It seems that dask release 2.5.0 broke cesium, at least on all my travis testing envs (both python 3.6 and 3.7, windows server ,osx, ubuntu 16).

The relevant part of the error I'm getting is:

```
from cesium import featurize

  File "/home/travis/virtualenv/python3.7.3/lib/python3.7/site-packages/cesium/featurize.py", line 8, in <module>

    from dask.compatibility import reraise

ImportError: cannot import name 'reraise' from 'dask.compatibility' (/home/travis/virtualenv/python3.7.3/lib/python3.7/site-packages/dask/compatibility.py)

/home/travis/.travis/functions: line 553:  4490 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"
```

I will try to force dask 2.4.0 install and see if this fixes the issue, I will update once I find a version that works & make a PR.

**Comment by acrellin** [comment]
Fixed in https://github.com/cesium-ml/cesium/commit/1db58fd3433f40c6f0f5e006c00681a55fc4dec0
