### ISSUE TITLE
Citation question -- I am citing your library in my publication

### ISSUE THREAD

**Issue by tatigabru** [cesium-ml/cesium#288]
Could you please provide the author's names and a year of the last release?
So far I only cite it with the link, but need to make it properly now. 

thank you for this library, by the way :)

**Comment by stefanv** [comment]
Thanks, @tatigabru, for using and citing our work!  Please use the [SciPy proceedings publication](http://conference.scipy.org/proceedings/scipy2016/brett_naul.html); there is BiBTeX available on that page.
