### ISSUE TITLE
pinned scikit-learn

### ISSUE THREAD

**Issue by paulkerry1** [cesium-ml/cesium#289]
Hi
Please consider not pinning scikit-learn==0.20.0 as done in...
https://github.com/cesium-ml/cesium/blob/master/requirements.txt

Pinning the older release of scikit-learn is causing problems on systems that require the latest version of scikit-learn for other python packages.

This is using python 3.7.3

Cheers
Paul.

**Comment by stefanv** [comment]
@paulkerry1 Sorry for the delay in responding; we can certainly unpin scikit-learn.  @acrellin Do you have a moment to take a look?

**Comment by acrellin** [comment]
@paulkerry1 this is now fixed in the latest master and in the newly released v0.9.12

**Comment by acrellin** [comment]
Fixed in https://github.com/cesium-ml/cesium/commit/fc3230bbfc0a246f83652d6f3523adc58d306e05

**Comment by paulkerry1** [comment]
Great - thanks very much.
Paul.
