### ISSUE TITLE
Error: Microsoft Visual C++ 14.0 is required.

### ISSUE THREAD

**Issue by KevinFumbles** [cesium-ml/cesium#290]
I'm not sure if I don't completely understand the build process, but when trying to build the latest version (v0.9.12) from source on Windows, pip errors with an error message stating that Microsoft Visual C++ 14.0 is required. I believe this is not correct since it is explicitly stated in the README that MSVC does not have the compiler required and that an alternative (e.g. MinGW) is necessary to build from source. I have seen this behavior on a fresh installation of Anaconda 5.2.0 as well as 2020.02.

Can this error be changed from suggesting to install MSVC to MinGW(-w64)?

I didn't think providing logs was necessary in this case, but if requested I can provide it.

**Comment by acrellin** [comment]
@KevinFumbles are you attempting to build from source (https://github.com/cesium-ml/cesium#installation-from-source) or just doing `pip install cesium`? Please follow the instructions to build from source here, after ensuring you have MinGW installed: https://github.com/cesium-ml/cesium#installation-from-source 
Let us know if that works for you.

**Comment by KevinFumbles** [comment]
Sorry, I misspoke earlier. For this scenario, it was just a `pip install cesium` that lead to the error about needing to install MSVC.

To clarify the source build instructions, do you need Cython AND MinGW, or does one suffice? If only one, am I correct in assuming that Cython would be the "correct" way?

**Comment by acrellin** [comment]
Cython runs on top of MinGW, so you need to install both.

**Comment by acrellin** [comment]
@KevinFumbles https://cython.readthedocs.io/en/latest/src/tutorial/appendix.html

**Comment by acrellin** [comment]
We've updated the installation instructions to be more clear here: https://github.com/cesium-ml/cesium/pull/291

**Comment by KevinFumbles** [comment]
Ok that makes sense. With that said, I have followed the build instructions, and I was able to install v0.9.6 but v0.9.12 fails with the following output. Since my original issue isn't relevant if the correct build procedure is taken, I'll go ahead and close this.
[failed.log](https://github.com/cesium-ml/cesium/files/4417171/failed.log)

**Comment by acrellin** [comment]
Were you successfully able to install from source following the new
instructions?
