### ISSUE TITLE
 provide RectangleGeometry  extrudedHeight gradient ramp Color Material   bottom-up (floor-sky) 

### ISSUE THREAD

**Issue by 4NK4** [cesium-ml/cesium#293]
![E{H9RDVVGO`3VZCUBWYU1`P](https://user-images.githubusercontent.com/28991681/102080948-55a04180-3e4a-11eb-8fb3-6ce631477eb5.png)

**Comment by 4NK4** [comment]
static GetRectangle3() {
    return new Cesium.Primitive({
      geometryInstances: new Cesium.GeometryInstance({
        geometry: new Cesium.RectangleGeometry({
          rectangle: Cesium.Rectangle.fromDegrees(121.5, 37.8, 121.7, 37.9),
          vertexFormat: Cesium.EllipsoidSurfaceAppearance.VERTEX_FORMAT,
          extrudedHeight: 150000,
          //stRotation: Math.PI * 0.5,
          height: 150.0,
        }),
        id: "rectangle",
        attributes: {
          color: Cesium.ColorGeometryInstanceAttribute.fromColor(
            Cesium.Color.fromRandom({
              alpha: 0.5,
            })
          ),
        },
      }),
      appearance: new Cesium.EllipsoidSurfaceAppearance({
        material: new Cesium.Material({
          fabric: {
            type: "Color",
            uniforms: {
              color: new Cesium.Color(0.0, 1.0, 0.0, 0.5),
            },
            source: `uniform vec4 color;czm_material czm_getMaterial(czm_materialInput materialInput)
            {
              czm_material material = czm_getDefaultMaterial(materialInput);
              material.diffuse = vec3(0.0,1.0 - materialInput.str.r ,1.0);
              return material;
            }`,
          },
        }),
      }),
    });
  }

**Comment by stefanv** [comment]
I think you meant to file this issue for another Cesium!
