### ISSUE TITLE
Cadence/Error features

### ISSUE THREAD

**Issue by pyaf** [cesium-ml/cesium#294]
Hi, 

I really liked this library. I was looking at the list of features supported right now and found the category of "Cadence/Error" features, I couldn't understand what kind of features were these and what Cadence meant here. Looked up at `cadence_features.py` but didn't understand it well. Could you please briefly explain to me exactly what kind of features are we talking about in this category or if you could redirect me to a source which talks about this feature category, it'd be good as well.

Thanks for this amazing library!

**Comment by acrellin** [comment]
These are features related to observational characteristics that vary from survey to survey. For more details see http://cesium-ml.org/docs/feature_table.html

**Comment by acrellin** [comment]
We're glad you've been enjoying the library! Please let us know if we can answer any other questions.
