### ISSUE TITLE
No screenshot, no use.

### ISSUE THREAD

**Issue by NeuroForLunch** [cesium-ml/cesium#299]
Screenshots show the current state of the project and are more accurate than descriptions given (for a lot of projects) so please upload some. This opinion is from wasting time on other projects that were nicely written about but after installing them, the functionality was not there.

https://github.com/cesium-ml/cesium_web doesn't have screenshots either.

**Comment by stefanv** [comment]
Thanks for the feedback.

You can see a notebook showing how to use the library here: http://cesium-ml.org/docs/auto_examples/plot_EEG_Example.html#sphx-glr-auto-examples-plot-eeg-example-py

The Cesium web application is not under active development at the moment.

**Comment by NeuroForLunch** [comment]
I saw that one but its just like a matplotlib screenshot... 

From https://bids.berkeley.edu/research/cesium-ml:

> Cesium-ML is an end-to-end machine learning platform for time-series, that computes machine learning features, builds models, and does prediction. Cesium has two main components—a Python library, and a web application platform that allows interactive exploration of machine learning pipelines. The Cesium library is specifically designed to handle irregularly sampled time series, as is common in astronomy.

Also...
<img width="251" alt="Screen Shot 2021-07-22 at 10 20 05 AM" src="https://user-images.githubusercontent.com/82769344/126681787-595bf633-7d6a-432a-a482-7590c282fc42.png">
<img width="1099" alt="Screen Shot 2021-07-22 at 10 17 28 AM" src="https://user-images.githubusercontent.com/82769344/126681804-c9f17119-bcc9-4df1-8589-122b9a64090c.png">

**Comment by stefanv** [comment]
Yes, the web application is a different project, and not currently maintained.  The library is, well, a library---so the notebook is about the best we can provide.

We should upgrade to HTTPS for the website; thanks for the reminder.

**Comment by stefanv** [comment]
I've upgraded the website; it will take a while to reflect but should now all be HTTPs.
