### ISSUE TITLE
Is cesium compatible with the current sklearn version (scikit-learn 1.1) ?

### ISSUE THREAD

**Issue by aaelony** [cesium-ml/cesium#304]
Hello, 

It appears cesium doesn't work with current versions of the dependencies (e.g. sklearn, dask).

For sklearn as an example:

https://github.com/cesium-ml/cesium/blob/master/cesium/featurize.py#L11 contains

```
from sklearn.impute import SimpleImputer as Imputer
```
as per https://stackoverflow.com/questions/59439096/importerror-cannnot-import-name-imputer-from-sklearn-preprocessing, 

`from sklearn.preprocessing import Imputer` was *deprecated with scikit-learn v0.20.4 and removed as of v0.22.2*.

```
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
```

is cesium compatible with the current versions of the dependencies (e.g. sklearn and dask)?

If not, is there a requirements.txt file or a dictionary of dependencies and versions known to work correctly?

**Comment by stefanv** [comment]
It looks as though this import works fine with sklearn 1.1.1.  Which version are you trying it with?

**Comment by aaelony** [comment]
I think at the time I reported this, sklearn 1.0.2 was the latest.

For me `conda install -y -c conda-forge cesium` fails.  Does it work on your end? Is installation via conda expected to work?  Once that works, I can retry with the latest release (e.g. sklearn 1.1.1).

**Comment by aaelony** [comment]
I see.  I tend to prefer Conda or Mamba and avoid `pip` because Conda does conflict resolution.

**Comment by aaelony** [comment]
I just tried a `pip install cesium` on a Mac running 12.4 Monterey (Apple M1 chip) that fails as well with "`no matching distribution found for cesium`".

**Comment by stefanv** [comment]
Is the latest release working for you?

**Comment by stefanv** [comment]
That's excellent, thanks!
