### ISSUE TITLE
Python 3.10 support?

### ISSUE THREAD

**Issue by egorananyev** [cesium-ml/cesium#307]
Installing through conda forge on python 3.10
`conda install -c conda-forge cesium`
I get the following:
>   - cesium -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']
> Your python: python=3.10

Installing through pip _seems_ to work, and I can `import cesium`, but none of the modules are recognized. E.g., running
`cesium.featurize.featurize_time_series()`
yields:
> module 'cesium' has no attribute 'featurize'

`ls /Users/username/Library/miniconda3/envs/sklearn/lib/python3.10/site-packages/cesium/`
> __init__.py        data_management.py features           setup.py           time_series.py     version.py
> __pycache__        datasets           _featurize.py_       tests              util.py

**Comment by stefanv** [comment]
This is not a bug; you have to do `import cesium.featurize` or `from cesium import featurize` to bring in the submodule.

**Comment by egorananyev** [comment]
Thanks, this worked! I copied the `import` code straight from a book called "Practical Time Series Analysis," but it didn't work in my case.

**Comment by stefanv** [comment]
Oh dear, that's not right! Please let the author know.

We can also add lazy loading of submodules, which will allow access to submodules. I'll file an issue.

**Comment by egorananyev** [comment]
I just realized I never posted the `import` code that's used in the book. Just including it in case anyone encountered the same issue (maybe it's a version thing):

`from cesium import featurize.featurize_time_series as ft`

This yields the following error:

> from cesium import featurize.featurize_time_series as ft
>                                        ^   
> SyntaxError: invalid syntax

(the ^ points to the period after "featurize")

Nielsen, Aileen. Practical Time Series Analysis
