### ISSUE TITLE
Implement a tool to provision & scale disco (now celery) worker farm

### ISSUE THREAD

**Issue by stefanv** [cesium-ml/cesium#31]
Ultimately, this type of scaling should happen automatically.

**Comment by acrellin** [comment]
No longer relevant.

**Comment by stefanv** [comment]
Do we have a similar tool for Celery?

**Comment by acrellin** [comment]
Azure has Autoscaling for its VMs, though I don't know the details. I'll reopen this til we're sure it covers our needs.

**Comment by stefanv** [comment]
See also:

- http://celery.readthedocs.org/en/latest/userguide/monitoring.html
- https://github.com/mher/flower#screenshots

**Comment by stefanv** [comment]
With our current setup, you can use any external tool to fire up more workers.  Closing for now, will open something on cesium-ml/cesium-web
