### ISSUE TITLE
Handle NaN or infinite feature values

### ISSUE THREAD

**Issue by bnaul** [cesium-ml/cesium#92]
Currently the user sees a generic "An error occurred while processing your request. Please try again at a later time." when trying to build a model using features that have invalid values (i.e., values that scikit-learn doesn't accept). Should either fail more verbosely or, preferably, retrain without those features and warn the user that they were omitted.

**Comment by bnaul** [comment]
In case anyone's curious why a feature would be infinite: a few features assume that the data are log-scale like magnitudes, and in converting large values back to linear scale we can over- or under-flow. So I think these features are behaving as expected, but just don't make sense for every application.

**Comment by bnaul** [comment]
Another issue: sometimes NaN or infinite values appear during the computation of a feature and this currently breaks the whole pipeline. Need to handle such errors more gracefully (how?).

**Comment by stefanv** [comment]
What is the current status here, Brett?

**Comment by bnaul** [comment]
Seems like this should be easy to fix, just need to decide what to do exactly:

- Notify user as soon as invalid feature values are detected? i.e., mid- or post-featurization
- Throw a (human-readable) exception informing the user which features are invalid?
- ...?

**Comment by stefanv** [comment]
How about both?  An error message that pops up, and then a little report when you click on the failed result?
